### ISSUE TITLE
Readme argument order disagrees with docstring

### ISSUE THREAD

**Issue by AI0867** [barry-scott/config-path#1]
According to [README.md](https://github.com/barry-scott/config-path/blob/master/README.md), the argument order for `ConfigPath` is `vendor, appname, filetype`:

```
Supports Windows, macOS and most unix systems using the 'XDG Base Directory Specification'.

ConfigPath( vendor, appname, filetype )
```

In [__init__.py](https://github.com/barry-scott/config-path/blob/master/config_path/__init__.py), the argument order is `appname, vendor, filetype`, though the arguments are listed in the other order in the docstring:
```
def __init__( self, appname, vendor, filetype ):
    '''
    The `vendor` should be the domain name of the application provider.
    The `appname` is the name the application is know by.
    The `filetype` is the use as the suffix for a config file.
    Typical filetypes are .json, .ini, .xml, etc.
        cfg_path = ConfigPath( 'widget-app', 'example.com', '.json' )
    '''
```

On a (mostly) unrelated note, `fileextension` or the like might be a better be a better name than `filetype`.

**Comment by barry-scott** [comment]
I have updated the README.md to match the code.
And release 1.0.2 with the doc fix.

fileextension vs. filetype is not clear cut. It used to be a reasonably reliable way to know the type of a file
was to examine its extention. That has broken down with the use of .json and .xml that tell you the encoding
rather then the type of a file, e.g. config in this packages case. But for .py .tar.gz .exe its telling you the type of
the file.
