### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by clemense** [barry-scott/config-path#3]
Hi!

When running multiple processes in parallel,  this:
https://github.com/barry-scott/config-path/blob/cf0824dec14fc5fd828cc0b6e7fdddc290e439bb/config_path/__init__.py#L146-L147
can lead to a race condition.

One solution would be to use
```
if mkdir and not os.path.exists( config_folder ):
            os.makedirs( config_folder,  exist_ok=True  )
```
instead.   (the `and not os.path.exists( config_folder )` could also be dropped in this case)

Let me know if a PR is welcome.

Thanks!

**Comment by barry-scott** [comment]
Fixed and 1.0.3 released.
